#

# Read & Write Schemas with Polars-Extensions

In [5]:
import polars as pl
import polars_extensions as plx

data = pl.read_csv('../datasets/employees.csv')
data

shape: (5, 8)
┌────────────┬────────────┬───────────┬────────────┬────────────┬────────────┬────────────┬────────┐
│ employee_i ┆ first_name ┆ last_name ┆ email      ┆ job_title  ┆ date_of_bi ┆ date_of_hi ┆ salary │
│ d          ┆ ---        ┆ ---       ┆ ---        ┆ ---        ┆ rth        ┆ re         ┆ ---    │
│ ---        ┆ str        ┆ str       ┆ str        ┆ str        ┆ ---        ┆ ---        ┆ i64    │
│ i64        ┆            ┆           ┆            ┆            ┆ str        ┆ str        ┆        │
╞════════════╪════════════╪═══════════╪════════════╪════════════╪════════════╪════════════╪════════╡
│ 1          ┆ john       ┆ doe       ┆ john.doe@e ┆ software_e ┆ 1990-05-12 ┆ 2015-08-01 ┆ 85000  │
│            ┆            ┆           ┆ xample.com ┆ ngineer    ┆            ┆            ┆        │
│ 2          ┆ jane       ┆ smith     ┆ jane.smith ┆ data_scien ┆ 1988-11-23 ┆ 2017-03-15 ┆ 95000  │
│            ┆            ┆           ┆ @example.c ┆ tist       ┆            ┆            ┆        │
│            ┆            ┆           ┆ om         ┆            ┆            ┆            ┆        │
│ 3          ┆ bob        ┆ johnson   ┆ bob.johnso ┆ product_ma ┆ 1985-07-19 ┆ 2012-10-10 ┆ 105000 │
│            ┆            ┆           ┆ n@example. ┆ nager      ┆            ┆            ┆        │
│            ┆            ┆           ┆ com        ┆            ┆            ┆            ┆        │
│ 4          ┆ alice      ┆ davis     ┆ alice.davi ┆ ux_designe ┆ 1992-04-06 ┆ 2020-01-21 ┆ 78000  │
│            ┆            ┆           ┆ s@example. ┆ r          ┆            ┆            ┆        │
│            ┆            ┆           ┆ com        ┆            ┆            ┆            ┆        │
│ 5          ┆ charlie    ┆ brown     ┆ charlie.br ┆ qa_enginee ┆ 1993-09-14 ┆ 2019-07-08 ┆ 72000  │
│            ┆            ┆           ┆ own@exampl ┆ r          ┆            ┆            ┆        │
│            ┆            ┆           ┆ e.com      ┆            ┆            ┆            ┆        │
└────────────┴────────────┴───────────┴────────────┴────────────┴────────────┴────────────┴────────┘

In [6]:
data.schema

Schema([('employee_id', Int64),
        ('first_name', String),
        ('last_name', String),
        ('email', String),
        ('job_title', String),
        ('date_of_birth', String),
        ('date_of_hire', String),
        ('salary', Int64)])

In [7]:
plx.write_schema(data,'schema.json')

In [8]:
schema = plx.read_schema('schema.json')
schema

Schema([('employee_id', Int64),
        ('first_name', String),
        ('last_name', String),
        ('email', String),
        ('job_title', String),
        ('date_of_birth', String),
        ('date_of_hire', String),
        ('salary', Int64)])

In [11]:
data = pl.read_csv('../datasets/employees.csv',schema=schema)
data

shape: (5, 8)
┌────────────┬────────────┬───────────┬────────────┬────────────┬────────────┬────────────┬────────┐
│ employee_i ┆ first_name ┆ last_name ┆ email      ┆ job_title  ┆ date_of_bi ┆ date_of_hi ┆ salary │
│ d          ┆ ---        ┆ ---       ┆ ---        ┆ ---        ┆ rth        ┆ re         ┆ ---    │
│ ---        ┆ str        ┆ str       ┆ str        ┆ str        ┆ ---        ┆ ---        ┆ i64    │
│ i64        ┆            ┆           ┆            ┆            ┆ str        ┆ str        ┆        │
╞════════════╪════════════╪═══════════╪════════════╪════════════╪════════════╪════════════╪════════╡
│ 1          ┆ john       ┆ doe       ┆ john.doe@e ┆ software_e ┆ 1990-05-12 ┆ 2015-08-01 ┆ 85000  │
│            ┆            ┆           ┆ xample.com ┆ ngineer    ┆            ┆            ┆        │
│ 2          ┆ jane       ┆ smith     ┆ jane.smith ┆ data_scien ┆ 1988-11-23 ┆ 2017-03-15 ┆ 95000  │
│            ┆            ┆           ┆ @example.c ┆ tist       ┆            ┆            ┆        │
│            ┆            ┆           ┆ om         ┆            ┆            ┆            ┆        │
│ 3          ┆ bob        ┆ johnson   ┆ bob.johnso ┆ product_ma ┆ 1985-07-19 ┆ 2012-10-10 ┆ 105000 │
│            ┆            ┆           ┆ n@example. ┆ nager      ┆            ┆            ┆        │
│            ┆            ┆           ┆ com        ┆            ┆            ┆            ┆        │
│ 4          ┆ alice      ┆ davis     ┆ alice.davi ┆ ux_designe ┆ 1992-04-06 ┆ 2020-01-21 ┆ 78000  │
│            ┆            ┆           ┆ s@example. ┆ r          ┆            ┆            ┆        │
│            ┆            ┆           ┆ com        ┆            ┆            ┆            ┆        │
│ 5          ┆ charlie    ┆ brown     ┆ charlie.br ┆ qa_enginee ┆ 1993-09-14 ┆ 2019-07-08 ┆ 72000  │
│            ┆            ┆           ┆ own@exampl ┆ r          ┆            ┆            ┆        │
│            ┆            ┆           ┆ e.com      ┆            ┆            ┆            ┆        │
└────────────┴────────────┴───────────┴────────────┴────────────┴────────────┴────────────┴────────┘