# How to Use Read XML in Polars

## Defaults

In [1]:
import polars_extensions as plx
import polars as pl

data = plx.read_xml('../../datasets/rss.xml')
data

shape: (17, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ rss.versi ┆ rss.chann ┆ rss.chann ┆ rss.chann ┆ … ┆ rss.chann ┆ rss.chann ┆ rss.chann ┆ rss.chan │
│ on        ┆ el.name   ┆ el.title. ┆ el.link.t ┆   ┆ el.item.i ┆ el.item.i ┆ el.item.i ┆ nel.item │
│ ---       ┆ ---       ┆ text      ┆ ext       ┆   ┆ tem.link. ┆ tem.descr ┆ tem.pubDa ┆ .item.ca │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ tex…      ┆ ipt…      ┆ te.…      ┆ tegory…  │
│           ┆           ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Sat, 29   ┆ Polars   │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2025  ┆          │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 19:35:40  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Sat, 29   ┆ Extensio │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2025  ┆ ns       │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 19:35:40  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Fri, 21   ┆ null     │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2025  ┆          │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 06:15:35  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Tue, 14   ┆ Polars   │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Oct 2025  ┆          │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 03:46:17  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Tue, 14   ┆ 1.52     │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Oct 2025  ┆          │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 03:46:17  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Mon, 23   ┆ null     │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Dec 2024  ┆          │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 05:03:31  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Tue, 03   ┆ null     │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Dec 2024  ┆          │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 06:31:33  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Tue, 03   ┆ null     │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Dec 2024  ┆          │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 03:54:41  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Sun, 24   ┆ null     │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2024  ┆          │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 04:39:57  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2.0       ┆ PYPI      ┆ PyPI      ┆ https://p ┆ … ┆ https://p ┆ The       ┆ Fri, 22   ┆ null     │
│           ┆           ┆ recent    ┆ ypi.org/p ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2024  ┆          │
│           ┆           ┆ updates   ┆ roject/po ┆   ┆ roject/po ┆ of Polars ┆ 21:56:50  ┆          │
│           ┆           ┆ for       ┆ lar…      ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│           ┆           ┆ polars…   ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Flatten

In [2]:
data = plx.read_xml('../../datasets/rss.xml',flatten=False)
data

shape: (1, 7)
┌─────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ rss.version ┆ rss.channel. ┆ rss.channel ┆ rss.channel ┆ rss.channel ┆ rss.channel ┆ rss.channel │
│ ---         ┆ name         ┆ .title.text ┆ .link.text  ┆ .descriptio ┆ .language.t ┆ .item       │
│ list[str]   ┆ ---          ┆ ---         ┆ ---         ┆ n.text      ┆ ext         ┆ ---         │
│             ┆ list[str]    ┆ list[str]   ┆ list[str]   ┆ ---         ┆ ---         ┆ list[struct │
│             ┆              ┆             ┆             ┆ list[str]   ┆ list[str]   ┆ [5]]        │
╞═════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ ["2.0"]     ┆ ["PYPI"]     ┆ ["PyPI      ┆ ["https://p ┆ ["Recent    ┆ ["en"]      ┆ [{["1.1.0"] │
│             ┆              ┆ recent      ┆ ypi.org/pro ┆ updates to  ┆             ┆ ,["https:// │
│             ┆              ┆ updates for ┆ ject/pol…   ┆ the Python… ┆             ┆ pypi.org…   │
│             ┆              ┆ pola…       ┆             ┆             ┆             ┆             │
└─────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

## Record Path

In [3]:
data = plx.read_xml('../../datasets/rss.xml' ,record_path='rss.channel.item')
data

shape: (17, 6)
┌──────────────┬────────────────┬────────────────┬────────────────┬────────────────┬───────────────┐
│ channel.name ┆ item.title.tex ┆ item.link.text ┆ item.descripti ┆ item.pubDate.t ┆ item.category │
│ ---          ┆ t              ┆ ---            ┆ on.text        ┆ ext            ┆ .category.tex │
│ str          ┆ ---            ┆ str            ┆ ---            ┆ ---            ┆ t             │
│              ┆ str            ┆                ┆ str            ┆ str            ┆ ---           │
│              ┆                ┆                ┆                ┆                ┆ str           │
╞══════════════╪════════════════╪════════════════╪════════════════╪════════════════╪═══════════════╡
│ PYPI         ┆ 1.1.0          ┆ https://pypi.o ┆ The Library of ┆ Sat, 29 Nov    ┆ Polars        │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2025 19:35:40  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
│ PYPI         ┆ 1.1.0          ┆ https://pypi.o ┆ The Library of ┆ Sat, 29 Nov    ┆ Extensions    │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2025 19:35:40  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
│ PYPI         ┆ 1.0.0          ┆ https://pypi.o ┆ The Library of ┆ Fri, 21 Nov    ┆ null          │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2025 06:15:35  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
│ PYPI         ┆ 0.9.0          ┆ https://pypi.o ┆ The Library of ┆ Tue, 14 Oct    ┆ Polars        │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2025 03:46:17  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
│ PYPI         ┆ 0.9.0          ┆ https://pypi.o ┆ The Library of ┆ Tue, 14 Oct    ┆ 1.52          │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2025 03:46:17  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
│ …            ┆ …              ┆ …              ┆ …              ┆ …              ┆ …             │
│ PYPI         ┆ 0.3.1          ┆ https://pypi.o ┆ The Library of ┆ Mon, 23 Dec    ┆ null          │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2024 05:03:31  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
│ PYPI         ┆ 0.3.0          ┆ https://pypi.o ┆ The Library of ┆ Tue, 03 Dec    ┆ null          │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2024 06:31:33  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
│ PYPI         ┆ 0.2.1          ┆ https://pypi.o ┆ The Library of ┆ Tue, 03 Dec    ┆ null          │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2024 03:54:41  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
│ PYPI         ┆ 0.2.0          ┆ https://pypi.o ┆ The Library of ┆ Sun, 24 Nov    ┆ null          │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2024 04:39:57  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
│ PYPI         ┆ 0.1.0          ┆ https://pypi.o ┆ The Library of ┆ Fri, 22 Nov    ┆ null          │
│              ┆                ┆ rg/project/pol ┆ Polars         ┆ 2024 21:56:50  ┆               │
│              ┆                ┆ ar…            ┆ Extensio…      ┆ GMT            ┆               │
└──────────────┴────────────────┴────────────────┴────────────────┴────────────────┴───────────────┘

In [4]:
data = plx.read_xml('../../datasets/rss.xml' ,record_path='rss.channel.item',flatten=False)
data

shape: (14, 6)
┌──────────────┬────────────────┬────────────────┬────────────────┬────────────────┬───────────────┐
│ channel.name ┆ item.title.tex ┆ item.link.text ┆ item.descripti ┆ item.pubDate.t ┆ item.category │
│ ---          ┆ t              ┆ ---            ┆ on.text        ┆ ext            ┆ ---           │
│ list[str]    ┆ ---            ┆ list[str]      ┆ ---            ┆ ---            ┆ list[struct[1 │
│              ┆ list[str]      ┆                ┆ list[str]      ┆ list[str]      ┆ ]]            │
╞══════════════╪════════════════╪════════════════╪════════════════╪════════════════╪═══════════════╡
│ ["PYPI"]     ┆ ["1.1.0"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Sat, 29 Nov  ┆ [{["Polars"]} │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2025 19:35:40  ┆ , {["Extensio │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆ ns"]…         │
│ ["PYPI"]     ┆ ["1.0.0"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Fri, 21 Nov  ┆ null          │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2025 06:15:35  ┆               │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆               │
│ ["PYPI"]     ┆ ["0.9.0"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Tue, 14 Oct  ┆ [{["Polars"]} │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2025 03:46:17  ┆ , {["1.52"]}, │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆ {["…          │
│ ["PYPI"]     ┆ ["0.8.0"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Thu, 07 Aug  ┆ null          │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2025 22:02:10  ┆               │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆               │
│ ["PYPI"]     ┆ ["0.7.0"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Wed, 16 Jul  ┆ null          │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2025 22:38:37  ┆               │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆               │
│ …            ┆ …              ┆ …              ┆ …              ┆ …              ┆ …             │
│ ["PYPI"]     ┆ ["0.3.1"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Mon, 23 Dec  ┆ null          │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2024 05:03:31  ┆               │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆               │
│ ["PYPI"]     ┆ ["0.3.0"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Tue, 03 Dec  ┆ null          │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2024 06:31:33  ┆               │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆               │
│ ["PYPI"]     ┆ ["0.2.1"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Tue, 03 Dec  ┆ null          │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2024 03:54:41  ┆               │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆               │
│ ["PYPI"]     ┆ ["0.2.0"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Sun, 24 Nov  ┆ null          │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2024 04:39:57  ┆               │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆               │
│ ["PYPI"]     ┆ ["0.1.0"]      ┆ ["https://pypi ┆ ["The Library  ┆ ["Fri, 22 Nov  ┆ null          │
│              ┆                ┆ .org/project/p ┆ of Polars      ┆ 2024 21:56:50  ┆               │
│              ┆                ┆ ol…            ┆ Extens…        ┆ GM…            ┆               │
└──────────────┴────────────────┴────────────────┴────────────────┴────────────────┴───────────────┘

In [5]:
data.drop('item.category').explode('item.title.text','item.link.text','item.description.text','item.pubDate.text')

shape: (14, 5)
┌──────────────┬─────────────────┬─────────────────────┬─────────────────────┬─────────────────────┐
│ channel.name ┆ item.title.text ┆ item.link.text      ┆ item.description.te ┆ item.pubDate.text   │
│ ---          ┆ ---             ┆ ---                 ┆ xt                  ┆ ---                 │
│ list[str]    ┆ str             ┆ str                 ┆ ---                 ┆ str                 │
│              ┆                 ┆                     ┆ str                 ┆                     │
╞══════════════╪═════════════════╪═════════════════════╪═════════════════════╪═════════════════════╡
│ ["PYPI"]     ┆ 1.1.0           ┆ https://pypi.org/pr ┆ The Library of      ┆ Sat, 29 Nov 2025    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 19:35:40 GMT        │
│ ["PYPI"]     ┆ 1.0.0           ┆ https://pypi.org/pr ┆ The Library of      ┆ Fri, 21 Nov 2025    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 06:15:35 GMT        │
│ ["PYPI"]     ┆ 0.9.0           ┆ https://pypi.org/pr ┆ The Library of      ┆ Tue, 14 Oct 2025    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 03:46:17 GMT        │
│ ["PYPI"]     ┆ 0.8.0           ┆ https://pypi.org/pr ┆ The Library of      ┆ Thu, 07 Aug 2025    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 22:02:10 GMT        │
│ ["PYPI"]     ┆ 0.7.0           ┆ https://pypi.org/pr ┆ The Library of      ┆ Wed, 16 Jul 2025    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 22:38:37 GMT        │
│ …            ┆ …               ┆ …                   ┆ …                   ┆ …                   │
│ ["PYPI"]     ┆ 0.3.1           ┆ https://pypi.org/pr ┆ The Library of      ┆ Mon, 23 Dec 2024    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 05:03:31 GMT        │
│ ["PYPI"]     ┆ 0.3.0           ┆ https://pypi.org/pr ┆ The Library of      ┆ Tue, 03 Dec 2024    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 06:31:33 GMT        │
│ ["PYPI"]     ┆ 0.2.1           ┆ https://pypi.org/pr ┆ The Library of      ┆ Tue, 03 Dec 2024    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 03:54:41 GMT        │
│ ["PYPI"]     ┆ 0.2.0           ┆ https://pypi.org/pr ┆ The Library of      ┆ Sun, 24 Nov 2024    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 04:39:57 GMT        │
│ ["PYPI"]     ┆ 0.1.0           ┆ https://pypi.org/pr ┆ The Library of      ┆ Fri, 22 Nov 2024    │
│              ┆                 ┆ oject/polar…        ┆ Polars Extensio…    ┆ 21:56:50 GMT        │
└──────────────┴─────────────────┴─────────────────────┴─────────────────────┴─────────────────────┘

## Include Attributes

In [6]:
data = plx.read_xml('../../datasets/rss.xml',include_attributes=False)
data

shape: (17, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ rss.chann ┆ rss.chann ┆ rss.chann ┆ rss.chann ┆ … ┆ rss.chann ┆ rss.chann ┆ rss.chann ┆ rss.chan │
│ el.title. ┆ el.link.t ┆ el.descri ┆ el.langua ┆   ┆ el.item.i ┆ el.item.i ┆ el.item.i ┆ nel.item │
│ text      ┆ ext       ┆ ption.tex ┆ ge.text   ┆   ┆ tem.link. ┆ tem.descr ┆ tem.pubDa ┆ .item.ca │
│ ---       ┆ ---       ┆ t         ┆ ---       ┆   ┆ tex…      ┆ ipt…      ┆ te.…      ┆ tegory…  │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Sat, 29   ┆ Polars   │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2025  ┆          │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 19:35:40  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Sat, 29   ┆ Extensio │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2025  ┆ ns       │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 19:35:40  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Fri, 21   ┆ null     │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2025  ┆          │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 06:15:35  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Tue, 14   ┆ Polars   │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Oct 2025  ┆          │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 03:46:17  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Tue, 14   ┆ 1.52     │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Oct 2025  ┆          │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 03:46:17  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Mon, 23   ┆ null     │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Dec 2024  ┆          │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 05:03:31  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Tue, 03   ┆ null     │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Dec 2024  ┆          │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 06:31:33  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Tue, 03   ┆ null     │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Dec 2024  ┆          │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 03:54:41  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Sun, 24   ┆ null     │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2024  ┆          │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 04:39:57  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PyPI      ┆ https://p ┆ Recent    ┆ en        ┆ … ┆ https://p ┆ The       ┆ Fri, 22   ┆ null     │
│ recent    ┆ ypi.org/p ┆ updates   ┆           ┆   ┆ ypi.org/p ┆ Library   ┆ Nov 2024  ┆          │
│ updates   ┆ roject/po ┆ to the    ┆           ┆   ┆ roject/po ┆ of Polars ┆ 21:56:50  ┆          │
│ for       ┆ lar…      ┆ Python P… ┆           ┆   ┆ lar…      ┆ Extensio… ┆ GMT       ┆          │
│ polars…   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘