# DataFramely

In [ ]:
pip install dataframely

## The Model

In [14]:
import dataframely as dy

class Request(dy.Schema):
    requestId = dy.Integer(primary_key=True)
    requestor = dy.String(nullable=False)
    requestType = dy.String(regex=r'\b(?:Add|Edit|Update|Delete)\b')
    description = dy.String(nullable=True)
    requestDate = dy.Date(nullable=False)

In [15]:
Request.polars_schema()

Schema([('requestId', Int64),
        ('requestor', String),
        ('requestType', String),
        ('description', String),
        ('requestDate', Date)])

## The Data

In [16]:
import polars as pl

df = pl.read_csv('../datasets/request_form.csv',try_parse_dates=True)
df

shape: (500, 5)
┌───────────┬───────────┬─────────────┬─────────────────────────┬─────────────┐
│ requestId ┆ requestor ┆ requestType ┆ description             ┆ requestDate │
│ ---       ┆ ---       ┆ ---         ┆ ---                     ┆ ---         │
│ i64       ┆ str       ┆ str         ┆ str                     ┆ date        │
╞═══════════╪═══════════╪═════════════╪═════════════════════════╪═════════════╡
│ 1         ┆ Bob       ┆ Edits       ┆ Edit an existing record ┆ 2024-06-02  │
│ 2         ┆ Bob       ┆ Edit        ┆ Edit an existing record ┆ 2024-11-18  │
│ 3         ┆ Eve       ┆ Deleted     ┆ Remove a record         ┆ 2024-08-26  │
│ 4         ┆ John      ┆ Update      ┆ Update a record         ┆ 2024-06-05  │
│ 5         ┆ Jane      ┆ Edit        ┆ Edit an existing record ┆ 2024-04-23  │
│ …         ┆ …         ┆ …           ┆ …                       ┆ …           │
│ 496       ┆ Jane      ┆ Edit        ┆ Edit an existing record ┆ 2024-08-20  │
│ 497       ┆ Alice     ┆ Delete      ┆ Remove a record         ┆ 2025-01-12  │
│ 498       ┆ John      ┆ Update      ┆ Update a record         ┆ 2025-01-14  │
│ 499       ┆ Alice     ┆ Edit        ┆ Edit an existing record ┆ 2024-10-24  │
│ 500       ┆ Bob       ┆ Edit        ┆ Edit an existing record ┆ 2024-09-16  │
└───────────┴───────────┴─────────────┴─────────────────────────┴─────────────┘

In [17]:
Request.validate(df)

RuleValidationError: 1 rules failed validation:
 * Column 'requestType' failed validation for 1 rules:
   - 'regex' failed for 2 rows

In [ ]:
successes, failures = Request.filter(df)

In [ ]:
successes

shape: (498, 5)
┌───────────┬───────────┬─────────────┬─────────────────────────┬─────────────┐
│ requestId ┆ requestor ┆ requestType ┆ description             ┆ requestDate │
│ ---       ┆ ---       ┆ ---         ┆ ---                     ┆ ---         │
│ i64       ┆ str       ┆ str         ┆ str                     ┆ date        │
╞═══════════╪═══════════╪═════════════╪═════════════════════════╪═════════════╡
│ 2         ┆ Bob       ┆ Edit        ┆ Edit an existing record ┆ 2024-11-18  │
│ 4         ┆ John      ┆ Update      ┆ Update a record         ┆ 2024-06-05  │
│ 5         ┆ Jane      ┆ Edit        ┆ Edit an existing record ┆ 2024-04-23  │
│ 6         ┆ Alice     ┆ Update      ┆ Update a record         ┆ 2024-04-13  │
│ 7         ┆ Jane      ┆ Delete      ┆ Remove a record         ┆ 2024-03-31  │
│ …         ┆ …         ┆ …           ┆ …                       ┆ …           │
│ 496       ┆ Jane      ┆ Edit        ┆ Edit an existing record ┆ 2024-08-20  │
│ 497       ┆ Alice     ┆ Delete      ┆ Remove a record         ┆ 2025-01-12  │
│ 498       ┆ John      ┆ Update      ┆ Update a record         ┆ 2025-01-14  │
│ 499       ┆ Alice     ┆ Edit        ┆ Edit an existing record ┆ 2024-10-24  │
│ 500       ┆ Bob       ┆ Edit        ┆ Edit an existing record ┆ 2024-09-16  │
└───────────┴───────────┴─────────────┴─────────────────────────┴─────────────┘

In [ ]:
type(failures)

dataframely.failure.FailureInfo

In [ ]:
failures.invalid()

shape: (2, 5)
┌───────────┬───────────┬─────────────┬─────────────────────────┬─────────────┐
│ requestId ┆ requestor ┆ requestType ┆ description             ┆ requestDate │
│ ---       ┆ ---       ┆ ---         ┆ ---                     ┆ ---         │
│ i64       ┆ str       ┆ str         ┆ str                     ┆ date        │
╞═══════════╪═══════════╪═════════════╪═════════════════════════╪═════════════╡
│ 1         ┆ Bob       ┆ Edits       ┆ Edit an existing record ┆ 2024-06-02  │
│ 3         ┆ Eve       ┆ Deleted     ┆ Remove a record         ┆ 2024-08-26  │
└───────────┴───────────┴─────────────┴─────────────────────────┴─────────────┘